/* Programming 3
 * CSCI 4611, Fall 2026, University of Minnesota
 * Instructor: Evan Suma Rosenberg <suma@umn.edu>
 * License: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
 */ 

import * as gfx from 'gophergfx'

export class App extends gfx.GfxApp
{
    // The graphics primitives that define objects in the scene 
    private ship: gfx.Mesh2;
    private star: gfx.Mesh2;
    private mine: gfx.Mesh2;

    // The stars will be drawn using a 2D particle system
    private starfield: gfx.Particles2;

    private mines: gfx.Node2;

    private mousePosition: gfx.Vector2;

    private timeSinceLastMineSpawn: number;

    // --- Create the App class ---
    constructor()
    {
        // Initialize the base class gfx.GfxApp
        super();

        this.ship = gfx.Geometry2Factory.createRectangle();
        this.star = gfx.Geometry2Factory.createRectangle();
        this.mine = gfx.Geometry2Factory.createRectangle();

        this.starfield = new gfx.Particles2(this.star, 1000);

        this.mines = new gfx.Node2();

        this.mousePosition = new gfx.Vector2();

        // Set the viewport to crop the scene to fit the window while maintaining aspect ratio
        this.renderer.viewport = gfx.Viewport.CROP;

        this.timeSinceLastMineSpawn = 0;
    }


    // --- Initialize the graphics scene ---
    createScene(): void 
    {
        // Set the ship's initial position and scale
        this.ship.position.set(0, 0);
        this.ship.scale.set(0.08, 0.08);

        // Set the scale of the template mine object
        this.mine.scale.set(0.12, 0.12);

        // Load the textures for the ship and star
        this.ship.material.texture = new gfx.Texture('./ship.png');
        this.star.material.texture = new gfx.Texture('./star.png');
        this.mine.material.texture = new gfx.Texture('./mine.png');

        // Starfield code generated by OpenAI Codex (GPT-6-Sol on medium effort)
        // It satisfies the functional requirement to generate 1000 stars with
        // random positions and sizes, but it is NOT a well-designed solution.
        // This will result in poor in-game performance because each star is a
        // separately rendered object in the scene.
        // const starTexture = new gfx.Texture('./star.png');
        // for(let i = 0; i < 1000; i++) {
        //     const star = gfx.Geometry2Factory.createRectangle();
        //     const size = 0.005 + Math.random() * 0.015;
        //     star.position.set(Math.random() * 2 - 1, Math.random() * 2 - 1);
        //     star.scale.set(size, size);
        //     star.material.texture = starTexture;
        //     this.scene.add(star);
        // }

        // Starfield code generated by Claude Code (Opus 5.5 on medium effort)
        // Each star is an instance that shares the base star's geometry and material.
        // This code is an improvement over the previous code, but it still has
        // performance issues because each star is a separate object in the scene.
        // const numStars = 10000;
        // for(let i=0; i < numStars; i++)
        // {
        //     const starInstance = this.star.createInstance();
        //     starInstance.position.set(Math.random() * 2 - 1, Math.random() * 2 - 1);

        //     const starSize = gfx.MathUtils.lerp(0.002, 0.01, Math.random());
        //     starInstance.scale.set(starSize, starSize);

        //     this.scene.add(starInstance);
        // }

        for(let i=0; i < this.starfield.numParticles; i++)
        {
            this.starfield.particleSizes[i] = Math.random()*0.008 + 0.002;
            this.starfield.particlePositions[i].set(Math.random()*2-1, Math.random()*2-1);
        }

        // Update the particle system position and sizes 
        this.starfield.update(true, true);

        this.scene.add(this.starfield);
        this.scene.add(this.mines);
        this.scene.add(this.ship);
        
    }

    
    // --- Update is called once each frame by the main graphics loop ---
    update(deltaTime: number): void 
    {
        const shipSpeed = 0.5; // normalized device units / sec
        const mineSpawnInterval = 0.5; //seconds

        if(this.ship.position.distanceTo(this.mousePosition) > 0.01) {
            this.ship.lookAt(this.mousePosition);

            const moveDirection = new gfx.Vector2(0, shipSpeed * deltaTime);
            moveDirection.rotate(this.ship.rotation);
            this.ship.position.add(moveDirection);
        }

        this.timeSinceLastMineSpawn += deltaTime;
        if(this.timeSinceLastMineSpawn >= mineSpawnInterval)
        {
            this.mineSpawn();
            this.timeSinceLastMineSpawn = 0;
        }

        //console.log('fps: ' + (1 / deltaTime).toFixed(2));
    }


    private mineSpawn(): void
    {
        const mineLimit = 20;

        // This creates a new instance of the base mine object.
        // Note that the Mine class extends the ShapeInstance class,
        // so only the original object will be created in GPU memory.
        const mineInstance = this.mine.createInstance();
        this.mines.add(mineInstance);

        // Compute a position for the mine within the 2D coordinate system bounds
        mineInstance.position.set(Math.random()*2-1, Math.random()*2-1);

        if(this.mines.children.length > mineLimit)
        {
            this.mines.children[0].remove();
        }

        console.log('Spawned mine at: ' + mineInstance.position.x + ', ' + mineInstance.position.y);
    }

    /**
     * Method called when the mouse is clicked. Subclasses can override this method to handle the event.
     * 
     * @param event - The MouseEvent object associated with the mouse click
     */
    onMouseDown(event: MouseEvent): void {
        this.mousePosition = this.getNormalizedDeviceCoordinates(event.x, event.y);

        console.log('Moving ship to position: ' + this.mousePosition.x + ', ' + this.mousePosition.y);
    }
}